name: flight
description: A Flight Scanner

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^4.3.2+2
  http: ^0.12.2
  geolocator: ^5.1.1
  geocoder: ^0.2.1
  permission_handler: ^5.0.1+1
  sqflite: ^1.3.2+1
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
      - family: OpenSans
        fonts:
        - asset: fonts/OpenSans-Regular.ttf
